name: icqs
description: "A Campus Queue System Flutter application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.2.3
  http: ^1.2.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.5.0

  # Firebase (MUST match each other)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.4
  cloud_functions: ^4.6.4
  firebase_messaging: ^14.7.10

  google_sign_in: ^6.1.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"
  image_path: "assets/icon.png"
  image_path_ios: "assets/icon.png"
